image: ruby:2.3

before_script:
  - bundle install

stages:
  - check
  - test

lint:
  stage: check
  script:
    - bundle exec rake lint
syntax:
  stage: check
  script:
    - bundle exec rake syntax
test:
  stage: test
  script:
    - bundle exec rake spec
